### PR TITLE
vala: fix build with latest vte3

### LINKED ISSUE #223: Doesn't compile with Vala 0.48.5
```
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/search_entry.vala:68.13-68.37: warning: `Gtk.Widget.margin_right' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/search_entry.vala:124.13-124.36: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/search_entry.vala:93.21-93.44: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/split_line.vala:31.13-31.23: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/command_panel.vala:302.40-302.63: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
            focus_term.term.feed_child(command_string.to_utf8());
                                       ^^^^^^^^^^^^^^^^^^^^^^^^
[ 45%] Generating ms-deepin-terminal.gmo
[ 46%] Generating pa-deepin-terminal.gmo
[ 48%] Generating nl-deepin-terminal.gmo
[ 47%] Generating pt_BR-deepin-terminal.gmo
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/window.vala:333.50-333.109: warning: Access to possible `null'. Perform a check or use an unsafe cast.
                    unowned X.Display xdisplay = (get_window().get_display() as Gdk.X11.Display).get_xdisplay();
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/window.vala:355.55-355.86: warning: `Gtk.Widget.get_margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/window.vala:355.92-355.124: warning: `Gtk.Widget.get_margin_right' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/window.vala:464.120-464.188: warning: unhandled error `GLib.KeyFileError'
            if (Utils.is_tiling_wm() || screen_monitor.is_composited() || window_is_fullscreen() || window_is_max() || config.config_file.get_boolean("advanced", "always_hide_resize_grip")) {
                                                                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Scanning dependencies of target ro
[ 48%] Built target pa
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/window.vala:65.13-65.39: warning: `Gdk.Screen.get_monitor_geometry' has been deprecated since 3.22
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/window.vala:59.36-59.101: warning: unhandled error `GLib.KeyFileError'
            tabbar_at_the_bottom = config.config_file.get_boolean("advanced", "tabbar_at_the_bottom");
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ 48%] Built target ms
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/confirm_dialog.vala:102.13-102.38: warning: `Gtk.Container.set_focus_chain' has been deprecated since 3.24
[ 49%] Generating ro-deepin-terminal.gmo
[ 49%] Built target pt_BR
[ 49%] Built target nl
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/./main.vala:41.5-41.20: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public void exit() {
    ^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/search_panel.vala:152.17-152.47: warning: `Vte.Terminal.search_set_gregex' has been deprecated since 0.46
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/encoding_panel.vala:118.50-118.77: warning: `Vte.Terminal.get_encoding' has been deprecated since 0.54
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/encoding_panel.vala:123.25-123.52: warning: `Vte.Terminal.set_encoding' has been deprecated since 0.54
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/remote_panel.vala:229.13-229.35: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
[ 49%] Built target ro
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:1558.17-1558.33: warning: `Vte.Terminal.set_encoding' has been deprecated since 0.54
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:1591.37-1591.59: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                    term.feed_child(login_command.to_utf8());
                                    ^^^^^^^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/remote_server_dialog.vala:411.13-411.32: warning: `Gtk.Window.set_default_geometry' has been deprecated since 3.20
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/remote_server_dialog.vala:397.17-397.42: warning: `Gtk.Container.set_focus_chain' has been deprecated since 3.24
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/remote_panel.vala:161.13-161.41: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/remote_panel.vala:162.13-162.42: warning: `Gtk.Widget.margin_right' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/remote_panel.vala:345.17-345.39: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/workspace.vala:693.17-693.41: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/workspace.vala:669.17-669.40: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/workspace.vala:760.17-760.39: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/about_widget.vala:51.13-51.125: warning: unhandled error `GLib.KeyFileError'
            bool dif_loaded = distribution_info_file.load_from_file("/usr/share/deepin/distribution.info", KeyFileFlags.NONE);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/about_widget.vala:51.13-51.125: warning: unhandled error `GLib.FileError'
            bool dif_loaded = distribution_info_file.load_from_file("/usr/share/deepin/distribution.info", KeyFileFlags.NONE);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/appbar.vala:147.49-147.119: warning: unhandled error `GLib.KeyFileError'
                    menu.set_prefer_deepin_menu(window.config.config_file.get_boolean("advanced", "prefer_deepin_menu"));
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/workspace.vala:144.56-144.79: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                        new_focus_term.term.feed_child(switch_command.to_utf8());
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/rename_dialog.vala:108.13-108.38: warning: `Gtk.Container.set_focus_chain' has been deprecated since 3.24
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/config_window.vala:578.29-578.55: warning: `Gdk.Screen.get_monitor_geometry' has been deprecated since 3.22
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/command_dialog.vala:224.17-224.42: warning: `Gtk.Container.set_focus_chain' has been deprecated since 3.24
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/command_panel.vala:131.13-131.42: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/command_panel.vala:132.13-132.43: warning: `Gtk.Widget.margin_right' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/command_panel.vala:193.17-193.39: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/workspace.vala:727.13-727.36: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/workspace.vala:735.13-735.36: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/workspace.vala:769.13-769.35: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/workspace.vala:777.13-777.35: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/workspace.vala:805.13-805.38: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/workspace.vala:813.13-813.38: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/workspace.vala:787.13-787.37: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/workspace.vala:795.13-795.37: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/workspace.vala:718.17-718.42: warning: `Gtk.Widget.margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:614.46-614.69: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                        this.term.feed_child(upload_command.to_utf8());
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:642.54-642.70: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                                this.term.feed_child(command.to_utf8());
                                                     ^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:465.41-465.111: warning: unhandled error `GLib.KeyFileError'
            menu.set_prefer_deepin_menu(window.config.config_file.get_boolean("advanced", "prefer_deepin_menu"));
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:687.50-687.73: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                            this.term.feed_child(switch_command.to_utf8());
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:692.58-692.83: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                                    this.term.feed_child(download_command.to_utf8());
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:697.66-697.88: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                                            this.term.feed_child(enter_command.to_utf8());
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:982.53-982.76: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                                    term.feed_child(command_string.to_utf8());
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:1093.50-1093.73: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                            this.term.feed_child(upload_command.to_utf8());
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:1108.42-1108.57: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                    this.term.feed_child(uris_s.to_utf8());
                                         ^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:1117.42-1117.55: error: Argument 1: Cannot convert from `char[]' to `unowned uint8[]?'
                    this.term.feed_child(data.to_utf8());
                                         ^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:1131.30-1131.50: warning: `Vte.Terminal.match_add_gregex' has been deprecated since 0.46
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:1133.21-1133.46: warning: `Vte.Terminal.match_set_cursor_type' has been deprecated since 0.54
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:1258.25-1258.39: warning: `Vte.Terminal.spawn_sync' has been deprecated since 0.48
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/terminal.vala:1191.25-1191.39: warning: `Vte.Terminal.spawn_sync' has been deprecated since 0.48
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/quake_window.vala:46.13-46.39: warning: `Gdk.Screen.get_monitor_geometry' has been deprecated since 3.22
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/quake_window.vala:225.50-225.109: warning: Access to possible `null'. Perform a check or use an unsafe cast.
                    unowned X.Display xdisplay = (get_window().get_display() as Gdk.X11.Display).get_xdisplay();
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/quake_window.vala:244.55-244.86: warning: `Gtk.Widget.get_margin_left' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/quake_window.vala:244.92-244.124: warning: `Gtk.Widget.get_margin_right' has been deprecated since 3.12
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/quake_window.vala:463.13-463.39: warning: `Gdk.Screen.get_monitor_geometry' has been deprecated since 3.22
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/quake_window.vala:287.34-287.61: warning: `Gdk.Screen.get_monitor_at_window' has been deprecated since 3.22
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/widget/quake_window.vala:290.13-290.39: warning: `Gdk.Screen.get_monitor_geometry' has been deprecated since 3.22
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/./main.vala:59.5-59.28: warning: DBus methods are recommended to throw at least `GLib.Error' or `GLib.DBusError, GLib.IOError'
    public void show_or_hide() {
    ^^^^^^^^^^^^^^^^^^^^^^^^
/build/deepin-terminal/src/deepin-terminal-5.0.4.1/./main.vala:280.17-280.42: warning: `Gtk.Window.set_has_resize_grip' has been deprecated since 3.14
Compilation failed: 12 error(s), 67 warning(s)
make[2]: *** [CMakeFiles/deepin-terminal.dir/build.make:142: main.c] Error 1
make[1]: *** [CMakeFiles/Makefile2:755: CMakeFiles/deepin-terminal.dir/all] Error 2
```

### PR DESCRIPTION
**Pull request by sgn**
In Vala (as of version 0.46.3), string::to_utf8() returns "char[]",
but Terminal::feed_child() expects "unowned uint8[]" instead.

VTE 0.60.0 has changed signature

I don't have much experience with Vala.
Here's a simple fix for this problem.

### CODE REVIEW

**Comment by worldofpeace** [comment]
You need to do conditional compilation to have this build with older versions.
This commit in elementary-terminal would be helpful https://github.com/elementary/terminal/commit/7dd6f93c9cd9e3d44407649a99ab0c3c17670a1a.
This LGTM.

**Comment by sgn** [comment]
I separated into 2 patches series.
I tried to build with vte3 0.59.{0,91,92} and 0.60.{0,1}

**Review by BLumia — APPROVED** [review]
